version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel_app:/var/www/laravel_app
    depends_on:
      - php
      - mysql
    
  
  php:
    build: 
      context: dockerfiles
      dockerfile: php8.3.Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel_app:cached
      # - ./php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0
    ports:
      - '3316:3306'
    volumes:
      - ./database/data:/var/lib/mysql
    env_file:
      - ./database/database.env


  artisan:
    build: 
      context: dockerfiles
      dockerfile: php8.3.Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel_app
    entrypoint: [php, /var/www/laravel_app/artisan]

  
  composer:
    build: 
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./database/data:/var/www/laravel_app

