version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./rea-projects.ru:/var/www/rea-projects.ru
      - ./rea-projects.ru/storage/logs:/var/www/rea-projects.ru/storage/logs
      - ./rea-projects.ru/storage/logs:/var/nginx/logs
      - ./rea-projects.ru/storage/app/public:/var/www/rea-projects.ru/docs/storage
      - ./rea-projects.ru/storage:/var/www/rea-projects.ru/storage
    depends_on:
      - php
      - mysql
    
  
  php:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./rea-projects.ru:/var/www/rea-projects.ru:cached
      - ./rea-projects.ru/storage/logs:/var/www/rea-projects.ru/storage/logs
      - ./rea-projects.ru/storage/app/public:/var/www/rea-projects.ru/docs/storage
      - ./rea-projects.ru/storage:/var/www/rea-projects.ru/storage

  mysql:
    image: mysql:8.0
    ports:
      - '3326:3306'
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - ./db/.env


  artisan:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./rea-projects.ru:/var/www/rea-projects.ru
      - ./rea-projects.ru/storage/logs:/var/www/rea-projects.ru/storage/logs
      - ./rea-projects.ru/storage/app/public:/var/www/rea-projects.ru/docs/storage
      - ./rea-projects.ru/storage:/var/www/rea-projects.ru/storage
    entrypoint: [php, /var/www/rea-projects.ru/artisan]

  
  composer:
    build: 
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./database/data:/var/www/rea-projects.ru